oidc:
  clientId: web
  clientSecret: secret
  issuerUrl: https://oidc-provider.com
  redirectUrl: https://domain.com/auth/callback
  cookieDomain: domain.com
nuki:
  apiKey: nuki api key
  smartLockDevice: smartLockId
web:
  address: ":8080"
storageType: memory
