apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: nupin
  name: nupin
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: nupin
